# Copyright (c) 2016 Pete Hanson
# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.2.4'
gem 'sinatra', '~>1.4.7'
gem 'sinatra-contrib'
gem 'erubis'

group :production do
  gem 'puma'
end
